project_id: '592879'
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
languages_mapping: &languages_mapping
  two_letters_code:
    zh: en
files:
  # JSON translation files
  - source: /i18n/zh/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
    languages_mapping: *languages_mapping
  # Docs Markdown files
  - source: /docs/**/*.md
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    languages_mapping: *languages_mapping
  # Docs Markdown files
  - source: /docs/**/*.mdx
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    languages_mapping: *languages_mapping